### ISSUE TITLE
Problem with Traefik v2.6.2

### ISSUE THREAD

**Issue by alexdelprete** [BetterCorp/cloudflarewarp#1]
Hi,

I was using this plugin: [https://github.com/vincentinttsh/cloudflareip]()

But when I upgraded to v2.6.2, it was creating problems to Traefik (same config):

```
time="2022-03-25T15:39:41+01:00" level=error msg="invalid CIDR address: 172.18.0.0/16║173.245.48.0/20║103.21.244.0/22║103.22.200.0/22║103.31.4.0/22║141.101.64.0/18║108.162.192.0/18║190.93.240.0/20║188.114.96.0/20║197.234.240.0/22║198.41.128.0/17║162.158.0.0/15║104.16.0.0/13║104.24.0.0/14║172.64.0.0/13║131.0.72.0/22" entryPointName=websecure routerName=traefik@file
```

So I found your plugin and tried it on v2.6.2 but I have the same issue. Did you test it on v2.6.2?

Thanks.

Alessandro

**Comment by mrinc** [comment]
Hey

I am actually not sure what v we are running right now, and were only using a single IP - since WARP not just for the real IP.

Can you send a snip of your config? (Specifically the plugin definition)

Will take a look and do some tests

**Comment by alexdelprete** [comment]
Pretty much like the example you wrote in the docs, except for one minor error I noticed in the example given, the name of the plugin in the middleware section. The difference is the list of IPs:

**Static:**

```
experimental:
  plugins:
    traefik-cf-warp:
      modulename: github.com/BetterCorp/cloudflarewarp
      version: v1.0.0
```

**Dynamic:**

```
http:
  routers:
    my-router:
      rule: Path(`/whoami`)
      service: service-whoami
      entryPoints:
        - http
      middlewares:
        - cloudflarewarp

  services:
   service-whoami:
      loadBalancer:
        servers:
          - url: http://127.0.0.1:5000
  
  middlewares:
    cloudflarewarp:
      plugin:
        traefik-cf-warp:
          trustip:
        # Internal Docker "proxy" network
        - "172.18.0.0/16"
        # CF Proxy IPs: https://www.cloudflare.com/ips
        - "173.245.48.0/20"
        - "103.21.244.0/22"
        - "103.22.200.0/22"
        - "103.31.4.0/22"
        - "141.101.64.0/18"
        - "108.162.192.0/18"
        - "190.93.240.0/20"
        - "188.114.96.0/20"
        - "197.234.240.0/22"
        - "198.41.128.0/17"
        - "162.158.0.0/15"
        - "104.16.0.0/13"
        - "104.24.0.0/14"
        - "172.64.0.0/13"
        - "131.0.72.0/22"
```

**Comment by mrinc** [comment]
Try incrementing your IP list by 2 spaces and see if that works?

**Comment by mrinc** [comment]
```
middlewares:  
    cloudflarewarp:  
      plugin:  
        traefik-cf-warp:  
          trustip:  
            # Internal Docker "proxy" network  
            - "172.18.0.0/16"  
            # CF Proxy IPs: https://www.cloudflare.com/ips  
            - "173.245.48.0/20"  
            - "103.21.244.0/22"  
            - "103.22.200.0/22"  
            - "103.31.4.0/22"  
            - "141.101.64.0/18"  
            - "108.162.192.0/18"  
            - "190.93.240.0/20"  
            - "188.114.96.0/20"  
            - "197.234.240.0/22"  
            - "198.41.128.0/17"  
            - "162.158.0.0/15"  
            - "104.16.0.0/13"  
            - "104.24.0.0/14"  
            - "172.64.0.0/13"  
            - "131.0.72.0/22"  
```

**Comment by alexdelprete** [comment]
Indentation doesn't seem the problem, I also tried shortening the list to two items:

```yaml
    cloudflarewarp:  
      plugin:  
        traefik-cf-warp:  
          trustip:  
            # Internal Docker "proxy" network  
            - "172.18.0.0/16"
            # CF Proxy IPs: https://www.cloudflare.com/ips  
            - "173.245.48.0/20"  
            # - "103.21.244.0/22"  
            # - "103.22.200.0/22"  
            # - "103.31.4.0/22"  
            # - "141.101.64.0/18"  
            # - "108.162.192.0/18"  
            # - "190.93.240.0/20"  
            # - "188.114.96.0/20"  
            # - "197.234.240.0/22"  
            # - "198.41.128.0/17"  
            # - "162.158.0.0/15"  
            # - "104.16.0.0/13"  
            # - "104.24.0.0/14"  
            # - "172.64.0.0/13"  
            # - "131.0.72.0/22"  
```

And the error was the same:

```
time="2022-03-27T00:51:13+01:00" level=error msg="invalid CIDR address: 172.18.0.0/16║173.245.48.0/20" entryPointName=websecure routerName=tasmoadmin@file
time="2022-03-27T00:51:13+01:00" level=error msg="invalid CIDR address: 172.18.0.0/16║173.245.48.0/20" routerName=proxmox2@file entryPointName=websecure
time="2022-03-27T00:51:13+01:00" level=error msg="invalid CIDR address: 172.18.0.0/16║173.245.48.0/20" entryPointName=websecure routerName=youtrack@file
```

Then I tried with only one element, and had no errors:

```
    cloudflarewarp:  
      plugin:  
        traefik-cf-warp:  
          trustip:  
            # Internal Docker "proxy" network
            - "172.18.0.0/16"
```

While testing this, I found out that I only need that line since I'm using cloudflared in docker, so I only need to trust that subnet. :)

The problem is for people who need more than one line. And the strange thing is that it was working with v2.6.1.
