### ISSUE TITLE
Traefik Log Still Showing Cloudflare IPs

### ISSUE THREAD

**Issue by mtthidoteu** [BetterCorp/cloudflarewarp#13]
Hello!
I feel bad being the only one opening an issue but I cannot get the plugin to work at all. I've enabled it correctly and I do not get any sort of error, however I cannot stop the Cloudflare IPs from showing, regardless of what I try.

Here are my configuration elements.
```
entryPoints:
  #Global Settings, Default Settings
  http:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: https
          scheme: https
  https:
    address: ":443"
    http:
      middlewares:
        - my-cloudflarewarp@file
```

with

```
    my-cloudflarewarp:
      plugin:
        cloudflarewarp:
          disableDefault: "false"
          trustip:
            - "1.1.1.1/24"
            - "173.245.48.0/20"
            - "103.21.244.0/22"
            - "103.22.200.0/22"
            - "103.31.4.0/22"
            - "141.101.64.0/18"
            - "108.162.192.0/18"
            - "190.93.240.0/20"
            - "188.114.96.0/20"
            - "197.234.240.0/22"
            - "198.41.128.0/17"
            - "162.158.0.0/15"
            - "104.16.0.0/13"
            - "104.24.0.0/14"
            - "172.64.0.0/13"
            - "131.0.72.0/22"
```

I ended up re-adding the Cloudflare IPs because it didn't work (just in case) but that hasn't helped anything. I'm just really at a loss now as to what to do.

**Comment by mrinc** [comment]
@mtthidoteu Just checking if you see the middleware listed (and linked) on one of your site routers?  
```my-cloudflarewarp@file```  

What I think could be happening is you need to specifically denote the middleware on each router you add - it's not globally added by default.

**Comment by mrinc** [comment]
Also... Update your config:

```
my-cloudflarewarp:  
      plugin:  
        cloudflarewarp:  
          disableDefault: false  
```  

We already provide all Cloud Flare IPs within the plugin itself so there is no need to define IPs unless you specifically have too.  

Also, you're using the IP like noted in #15  - which has been removed.
