### ISSUE TITLE
Still got panic every time when ws disconnected. v1.3.3

### ISSUE THREAD

**Issue by ncwhale** [BetterCorp/cloudflarewarp#17]
Well, I updated `traefik` & this plugin to `v1.3.3` , but still got this panic every time the ws is disconnected.

```
traefik  | time="2022-10-06T14:04:42Z" level=error msg="plugins-storage/sources/gop-215151865/src/github.com/BetterCorp/cloudflarewarp/cloudflarewarp.go:89:17: panic" plugin=plugin-cloudflarewarp module=github.com/BetterCorp/cloudflarewarp
traefik  | time="2022-10-06T14:04:46Z" level=error msg="plugins-storage/sources/gop-215151865/src/github.com/BetterCorp/cloudflarewarp/cloudflarewarp.go:89:17: panic" plugin=plugin-cloudflarewarp module=github.com/BetterCorp/cloudflarewarp
traefik  | time="2022-10-06T14:04:51Z" level=error msg="plugins-storage/sources/gop-215151865/src/github.com/BetterCorp/cloudflarewarp/cloudflarewarp.go:89:17: panic" plugin=plugin-cloudflarewarp module=github.com/BetterCorp/cloudflarewarp
```

How to reproduce this bug:

1. Create any service with WebSocket auto connected and proxy by traefik;
2. Add this plugin as middleware for cloudflare ip reverse;
3. Add this site proxy by cloudflare;
4. Open the service through cloudflare proxy DNS name;
5. Just `Refresh` the page which will case the WS disconnect, and the panic happens.

_Originally posted by @ncwhale in https://github.com/BetterCorp/cloudflarewarp/issues/14#issuecomment-1270120642_

Right now I just create a new route as walk-around solution for this BUG: the websocket PathPrefix will got a new route without this middleware  in path to avoid it. Like this:

```
    some-service-websocket:
      rule: Host(`subdomain.origin`) && Path(`/api/ws-stream`)
      service: some-service
      entryPoints:
        - websecure
      middlewares:
        - strip-api
        # - cloudflarewarp@file
```
