### ISSUE TITLE
Recommendation: Include necessary setting for Traefik in the documentation.

### ISSUE THREAD

**Issue by JBMEIZO** [BetterCorp/cloudflarewarp#21]
Hello all,

first of all I would like to thank you for this wonderful plugin.

I had a few problems with the setup for this plugin until it worked cleanly.
So that the headers can be rewritten cleanly the EntryPoint for Traefik must be configured. The Cloudflare addresses must be added as "TrustedIPs".

See the following example:

```
entryPoints:
  https:
    address: ":443"
    forwardedHeaders:
      trustedIPs:
        - "<cloudflare-ip>"
```

The background of this issue is to draw attention to this configuration so that other people do not encounter the same problem.

Maybe you can add this configuration to your documentation.

Many greetings
Marcel
