### ISSUE TITLE
Configuration Help

### ISSUE THREAD

**Issue by FirbyKirby** [BetterCorp/cloudflarewarp#23]
I've been trying to implement this plugin on my traefik network and I haven't been successful (host logs still show CF IPs rather then client IPs.) I was hoping someone could take a peek at my config files and tell me where I've gone wrong? Note that I see no errors or indications of the plugin in the log at any logging level.

One thing I'll note is that I am attempting to apply this middleware across all https traffic by defining it at the https entrypoint, and not at the service/router combo. Most of my hosts are other containers and I rely on the docker provider to handle those services, not service/router combos.

## Static Config
**NOTE:** certificate config, logging config, and dashboard config removed for irrelevance.

```
global:
  checkNewVersion: true
  sendAnonymousUsage: true

serversTransport:
  insecureSkipVerify: true

entryPoints:
  # Not used in apps, but redirect everything from HTTP to HTTPS
  http:
    address: :80
    forwardedHeaders:
      trustedIPs: &trustedIps
        # Start of Clouflare public IP list for HTTP requests, remove this if you don't use it
        - 173.245.48.0/20
        - 103.21.244.0/22
        - 103.22.200.0/22
        - 103.31.4.0/22
        - 141.101.64.0/18
        - 108.162.192.0/18
        - 190.93.240.0/20
        - 188.114.96.0/20
        - 197.234.240.0/22
        - 198.41.128.0/17
        - 162.158.0.0/15
        - 104.16.0.0/13
        - 104.24.0.0/14
        - 172.64.0.0/13
        - 131.0.72.0/22
        - 2400:cb00::/32
        - 2606:4700::/32
        - 2803:f800::/32
        - 2405:b500::/32
        - 2405:8100::/32
        - 2a06:98c0::/29
        - 2c0f:f248::/32
        # End of Cloudlare public IP list
    http:
      redirections:
        entryPoint:
          to: https
          scheme: https

  # HTTPS endpoint, with domain wildcard
  https:
    address: :443
    forwardedHeaders:
      # Reuse list of Cloudflare Trusted IP's above for HTTPS requests
      trustedIPs: *trustedIps
    http:
      middlewares:
        - securityHeaders@file
        - cloudflarewarp@file

providers:
  providersThrottleDuration: 2s

  # File provider for connecting things that are outside of docker / defining middleware
  file:
    filename: /etc/traefik/fileConfig.yml
    watch: true

  # Docker provider for connecting all apps that are inside of the docker network
  docker:
    watch: true
    network: proxy    # Add Your Docker Network Name Here
    # Default host rule to containername.domain.example
    defaultRule: "Host(`{{ lower (trimPrefix `/` .Name )}}.HOSTNAME.TLD`)"    # Replace with your domain
    swarmModeRefreshSeconds: 15s
    exposedByDefault: false
    #endpoint: "tcp://dockersocket:2375" # Uncomment if you are using docker socket proxy

#Traefik Plugins
experimental:
  plugins:
    #Get the real IP of the client from Cloudflare and pass that to the host.
    cf-warp:
      moduleName: github.com/BetterCorp/cloudflarewarp
      version: v1.3.0
```

## Dynamic Config
**NOTE:** Additional routers/services removed for redundancy, as well as some unused, but defined middleware.

```
http:

  ## EXTERNAL ROUTING - Only use if you want to proxy something manually ##
  routers:
    # Home Assistant routing
    homeassistant:
      entryPoints:
        - https
      rule: 'Host(`HOST.DOMAIN.TLD`)'
      service: homeassistant
      middlewares:
        #- "authentik"  #Uncomment when your ready to use authentik.

  ## SERVICES ##
  services:
    # Home Assistant service
    homeassistant:
      loadBalancer:
        servers:
          - url: http://192.168.1.4:8123/

  ## MIDDLEWARES ##
  middlewares:
    # Only Allow Local networks
    local-ipwhitelist:
      ipWhiteList:
        sourceRange:
          - 127.0.0.1/32 # localhost
          - 192.168.1.1/24 # LAN Subnet
          - 10.0.0.1/24 # LAN subnet

    #Authentik auth guard
    authentik:
      forwardauth:
        address: http://authentik:9000/outpost.goauthentik.io/auth/traefik
        trustForwardHeader: true
        authResponseHeaders:
          - X-authentik-username
          - X-authentik-groups
          - X-authentik-email
          - X-authentik-name
          - X-authentik-uid
          - X-authentik-jwt
          - X-authentik-meta-jwks
          - X-authentik-meta-outpost
          - X-authentik-meta-provider
          - X-authentik-meta-app
          - X-authentik-meta-version

    # Security headers
    securityHeaders:
      headers:
        customResponseHeaders:
          X-Robots-Tag: "none,noarchive,nosnippet,notranslate,noimageindex"
          X-Forwarded-Proto: "https"
          server: ""
        sslProxyHeaders:
          X-Forwarded-Proto: https
        referrerPolicy: "same-origin"
        hostsProxyHeaders:
          - "X-Forwarded-Host"
        customRequestHeaders:
          X-Forwarded-Proto: "https"
        contentTypeNosniff: true
        browserXssFilter: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsSeconds: 63072000
        stsPreload: true
    
    gzip:
      compress: {}

    cloudflarewarp:
      plugin:
        cf-warp:
          disableDefault: false

# Only use secure ciphers - https://ssl-config.mozilla.org/#server=traefik&version=2.6.0&config=intermediate&guideline=5.6              
tls:
  options:
    default:
      minVersion: VersionTLS12
      cipherSuites:
        - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
        - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
```

Any suggestions on getting this integrated globally would be greatly beneficial. If I can't get it defined globally, I'd love to get it implemented as middleware for all the dockers traefik is proxying via the docker provider.

**Comment by mrinc** [comment]
So, it looks doable globally on an entrypoint.... but ... 

```
    http:  
      middlewares:  
        - securityHeaders@file  
        - cloudflarewarp@file  
```

```
#Traefik Plugins  
experimental:  
  plugins:  
    #Get the real IP of the client from Cloudflare and pass that to the host.  
    cf-warp:  
      moduleName: github.com/BetterCorp/cloudflarewarp  
      version: v1.3.0  
```

Your plugin name defined here is cf-warp not cloudflarewarp as you are trying to reference it.  

What I recommend doing is change the plugins name to cloudflarewarp and then see if the logs on traefik boot say anything.  

```
#Traefik Plugins  
experimental:  
  plugins:  
    #Get the real IP of the client from Cloudflare and pass that to the host.  
    cloudflarewarp:  
      moduleName: github.com/BetterCorp/cloudflarewarp  
      version: v1.3.0  
```  

ref:  
https://doc.traefik.io/traefik/routing/entrypoints/#middlewares  
https://github.com/BetterCorp/cloudflarewarp/blob/master/test/traefik.toml
