### ISSUE TITLE
Traefik logs show only Cloudflare IPs

### ISSUE THREAD

**Issue by maxcountryman** [BetterCorp/cloudflarewarp#25]
Hi,

There is at least one other issue that seems to be related to this, but per that thread I'm opening a new issue here.

I'm only seeing Cloudflare's IPs in Traefik logs. My setup is pretty simple: Cloudflare is pointing to a VPS where Traefik is running and reverse proxying to a Node service running via Compose.

Traefik logs look like this:

```json
{
    "docker": {
        "container_created_at": "2023-07-08T14:49:56.646123162Z",
        "container_id": "3c0521b6f5468dc37780125eb6ab5f1740d85474b884c8781902bc782a426da0",
        "container_name": "traefik",
        "host": "[redacted]",
        "image": "traefik:v2.9",
        "label": {
            "com.docker.compose.config-hash": "513eeced38f574713fa07a7331a6e99f4e90c8a4825b1f8d0e1cf2970441a69d",
            "com.docker.compose.container-number": "1",
            "com.docker.compose.depends_on": "",
            "com.docker.compose.image": "sha256:d1e26b5f8193d713eb8f39d0ab0e3d513278f86e41644b07e189e1aef536b335",
            "com.docker.compose.oneoff": "False",
            "com.docker.compose.project": "traefik",
            "com.docker.compose.project.config_files": "/root/remotejobs.org/docker-compose.traefik.yml",
            "com.docker.compose.project.working_dir": "/root/remotejobs.org",
            "com.docker.compose.replace": "408d95cf3f8529a7bee7b15c97d64b40def048ba073756b78d7a7e7e29e781b7",
            "com.docker.compose.service": "traefik",
            "com.docker.compose.version": "2.16.0",
            "org.opencontainers.image.description": "A modern reverse-proxy",
            "org.opencontainers.image.documentation": "https://docs.traefik.io",
            "org.opencontainers.image.source": "https://github.com/traefik/traefik",
            "org.opencontainers.image.title": "Traefik",
            "org.opencontainers.image.url": "https://traefik.io",
            "org.opencontainers.image.vendor": "Traefik Labs",
            "org.opencontainers.image.version": "v2.9.10",
            "traefik.http.routers.api.rule": "Host(`localhost`)",
            "traefik.http.routers.api.service": "api@internal"
        },
        "stream": "stdout"
    },
    "dt": "2023-07-08T15:00:26.006223797Z",
    "message": {
        "ClientAddr": "172.69.23.115:63322",
        "ClientHost": "172.69.23.115",
        "ClientPort": "63322",
        "ClientUsername": "-",
        "DownstreamContentSize": 59561,
        "DownstreamStatus": 200,
        "Duration": 223792683,
        "OriginContentSize": 59561,
        "OriginDuration": 223756972,
        "OriginStatus": 200,
        "Overhead": 35711,
        "RequestAddr": "remotejobs.org",
        "RequestContentSize": 0,
        "RequestCount": 80,
        "RequestHost": "remotejobs.org",
        "RequestMethod": "GET",
        "RequestPath": "/remote-jobs/remote-clinical-reviewer-precertification-rn-massachusetts-2507",
        "RequestPort": "-",
        "RequestProtocol": "HTTP/1.1",
        "RequestScheme": "http",
        "RetryAttempts": 0,
        "RouterName": "web@docker",
        "ServiceAddr": "192.168.176.4:3000",
        "ServiceName": "web@docker",
        "ServiceURL": {
            "ForceQuery": false,
            "Fragment": "",
            "Host": "192.168.176.4:3000",
            "OmitHost": false,
            "Opaque": "",
            "Path": "",
            "RawFragment": "",
            "RawPath": "",
            "RawQuery": "",
            "Scheme": "http",
            "User": null
        },
        "StartLocal": "2023-07-08T15:00:25.782072405Z",
        "StartUTC": "2023-07-08T15:00:25.782072405Z",
        "entryPointName": "web",
        "level": "info",
        "msg": "",
        "time": "2023-07-08T15:00:26Z"
    },
    "platform": "Docker"
}
```

My Traefik compose:

```yml
version: "3"

services:
  traefik:
    container_name: traefik
    platform: linux/amd64
    image: traefik:v2.9
    labels:
      - "traefik.http.routers.api.rule=Host(`localhost`)"
      - "traefik.http.routers.api.service=api@internal"
    networks:
      - webgateway
    ports:
      - "80:80"
      - "127.0.0.1:8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./config/traefik/traefik.yml:/traefik.yml
      - ./config/traefik/:/etc/traefik/mconfig
    restart: unless-stopped

networks:
  webgateway:
    driver: bridge
```

My `traefik.yml`:

```yml
log:
  level: INFO
  format: "json"

accessLog:
  format: "json"
  fields:
    defaultMode: "keep"

api:
  dashboard: true
  insecure: true

entryPoints:
  web:
    address: ":80"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    watch: true
    network: traefik_webgateway

  file:
    directory: "/etc/traefik/mconfig/"
    watch: true

experimental:
  plugins:
    cloudflarewarp:
      modulename: github.com/BetterCorp/cloudflarewarp
      version: v1.3.0
```

My `file.yml`:

```yml
http:
  middlewares:
    cloudflarewarp:
      plugin:
        cloudflarewarp:
          disableDefault: false
```

Finally the Docker compose running the Node service:

```yml
version: "3"

services:
  blue-web: &web
    container_name: blue-web
    platform: linux/amd64
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
      network: host
    labels:
      - "traefik.enable=true"

      - "traefik.http.routers.web.rule=PathPrefix(`/`)"
      - "traefik.http.routers.web.entrypoints=web"
      - "traefik.http.routers.web.middlewares=cloudflarewarp@file"

      - "traefik.http.middlewares.test-retry.retry.attempts=5"
      - "traefik.http.middlewares.test-retry.retry.initialinterval=200ms"

      - "traefik.http.services.web.loadbalancer.server.port=3000"
      - "traefik.http.services.web.loadbalancer.passhostheader=true"
      - "traefik.http.services.web.loadbalancer.healthCheck.path=/health"
      - "traefik.http.services.web.loadbalancer.healthCheck.interval=10s"
      - "traefik.http.services.web.loadbalancer.healthCheck.timeout=1s"
    env_file:
      - .env
    restart: always
    networks:
      - traefik
      - internal

  green-web:
    <<: *web
    container_name: green-web

networks:
  traefik:
    name: traefik_webgateway
    external: true

  internal:
    external: false
```

It's not entirely clear what should happen, but what I would like is for the `X-Forwarded-For` (or `CF-Connecting-IP`) value to be visible somewhere in the Traefik logs.
