### ISSUE TITLE
modulename / moduleName ??

### ISSUE THREAD

**Issue by ThierryIT** [BetterCorp/cloudflarewarp#26]
Hello,

It seems that you shoud use "moduleName" instead of "modulename" ??
Using "code-server".
Thx for your work.

**Comment by IJMacD** [comment]
When installing as a HelmChart, neither `modulename` nor `moduleName` worked for me under the `plugins` key in the chart values. I had to install using additional cli arguments (and `moduleName`).

```
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    additionalArguments:
      - "--experimental.plugins.cloudflarewarp.moduleName=github.com/BetterCorp/cloudflarewarp"
      - "--experimental.plugins.cloudflarewarp.version=v1.3.0"
    hostNetwork: true
    experimental:
      plugins:
        # cloudflarewarp:
        #   moduleName: github.com/BetterCorp/cloudflarewarp
        #   version: v1.3.0
        enabled: true
    logs:
      access:
        enabled: true
```
