### ISSUE TITLE
Config being completely ignored

### ISSUE THREAD

**Issue by DrWarpMan** [BetterCorp/cloudflarewarp#28]
The plugin is doing it's job, but I am unable to configure it based on the documentation.

Docs say I should set `disableDefault` to `true`, if I don't want to use the plugin's default list of Cloudflare IPs.
When I do that, everything remains the same, `X-Real-Ip` is still getting replaced, and the header `X-Is-Trusted` is always `true`.

With my current configuration, I would expect header `X-Is-Trusted` to be `false`, and `X-Real-Ip` would not get overriden.

Here is my configuration:

`docker-compose.yml`
```yaml
services:
  traefik:
    image: traefik:v2.10.4
    # ...
    command:
      # ...
      - --entryPoints.websecure.http.middlewares=cloudflarewarp@file
      - --experimental.plugins.cloudflarewarp.modulename=github.com/BetterCorp/cloudflarewarp
      - --experimental.plugins.cloudflarewarp.version=v1.3.3
```

`middlewares.yml`
```yaml
http:
  middlewares:
    cloudflarewarp:
      plugin:
        cloudflarewarp:
          disableDefault: true
          trustip:
            - 103.245.48.0/24 # I put a random IP here on purpose
```

`whoami image response:`
```yaml
Cf-Connecting-Ip: 183.224.75.44
Cf-Ipcountry: DE
# ...
X-Forwarded-For: 183.224.75.44, 172.71.160.83
X-Forwarded-Host: whoami.<redacted>
X-Forwarded-Port: 443
X-Forwarded-Proto: https
# ...
X-Is-Trusted: yes
X-Real-Ip: 183.224.75.44
```
