### ISSUE TITLE
Traefik logs show only Cloudflare IPs

### ISSUE THREAD

**Issue by casudo** [BetterCorp/cloudflarewarp#29]
Reference to #13 and #25.

I have the same issues as the issues above. I still only see the Cloudflare IPs in my Traefik access.log. Traefik v2.10.5.

My traefik.yml:
```yaml
entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
      middlewares:
        - my-cloudflarewarp@file
  websecure:
    address: :443
    http:
      middlewares:
        - my-cloudflarewarp@file

experimental:
  plugins:
    cloudflarewarp:
      moduleName: "github.com/BetterCorp/cloudflarewarp"
      version: "v1.3.3"
```

my config.yml:
```yaml
http:
  middlewares:
    my-cloudflarewarp:
      plugin:
        cloudflarewarp:
          disableDefault:  "true"
          trustip:
            -  2400:cb00::/32 
            -  2606:4700::/32 
            -  2803:f800::/32 
            -  2405:b500::/32 
            -  2405:8100::/32 
            -  2a06:98c0::/29 
            -  2c0f:f248::/32 
            -  173.245.48.0/20 
            -  103.21.244.0/22 
            -  103.22.200.0/22 
            -  103.31.4.0/22 
            -  141.101.64.0/18 
            -  108.162.192.0/18 
            -  190.93.240.0/20 
            -  188.114.96.0/20 
            -  197.234.240.0/22 
            -  198.41.128.0/17 
            -  162.158.0.0/15 
            -  104.16.0.0/13 
            -  104.24.0.0/14 
            -  172.64.0.0/13 
            -  131.0.72.0/22
```
