### ISSUE TITLE
IP Address of cloudflared client displayed in traefik logs

### ISSUE THREAD

**Issue by maretodoric** [BetterCorp/cloudflarewarp#30]
Hello,

I have cloudflared running in docker container and all tunnels are configured online in cloudflare.
In same docker stack i have traefik and nginx running, however when checking traefik access logs i se IP address of docker router as accessing the endpoint.

Middleware is configured in file provider and when looking at traefik api page, i see "cloudflarewarp" middleware loaded.

Here is the content of docker-compose.yml:

```
version: '3.8'

services:
  traefik:
    image: traefik:v2.10
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.file.directory=/config"
      - "--providers.file.watch=true"
      - "--entrypoints.http.address=:80"
      - "--entrypoints.https.address=:443"
      - "--certificatesresolvers.resolver.acme.dnschallenge=true"
      - "--certificatesresolvers.resolver.acme.dnschallenge.provider=cloudflare"
      - "--certificatesresolvers.resolver.acme.dnschallenge.resolvers=1.1.1.1:53,8.8.8.8:53"
      - "--certificatesresolvers.resolver.acme.email=email@gmail.com"
      - "--certificatesresolvers.resolver.acme.storage=/letsencrypt/acme.json"
      - "--experimental.plugins.cloudflarewarp.modulename=github.com/BetterCorp/cloudflarewarp"
      - "--experimental.plugins.cloudflarewarp.version=v1.3.3"
      - "--accesslog=true"
      - "--accesslog.fields.headers.defaultmode=keep"
    environment:
      CF_API_EMAIL: email@gmail.com
      CF_DNS_API_TOKEN: <secret_token>
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /mnt/2TB/opt/controller/traefik/data/letsencrypt:/letsencrypt
      - /mnt/2TB/opt/controller/traefik/data/config:/config
    restart: on-failure
  cloudflared:
    image: cloudflare/cloudflared:latest
    restart: on-failure
    command: tunnel --no-autoupdate run --token <token>
  public_html:
    image: flashspys/nginx-static:latest
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.public_html.rule=Host(`domain.org`)"
      - "traefik.http.routers.public_html.entrypoints=https"
      - "traefik.http.routers.public_html.middlewares=hsts@file,cfip@file"
      - "traefik.http.routers.public_html.tls.certresolver=resolver"
      - "traefik.http.routers.public_html.tls.domains[0].main=domain.org"
      - "traefik.http.routers.public_html.tls.domains[0].sans=*.domain.org"
    volumes:
      - /mnt/2TB/opt/controller/public_html:/static
    restart: on-failure
```

Content of /config/middlewares.yml:
```
http:
  middlewares:
    cfip:
      plugin:
        cloudflarewarp:
          disableDefault: true
          trustips:
            - "172.25.0.0/32"
    hsts:
      headers:
        browserXSSFilter: true
        contentTypeNosniff: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsSeconds: 63072000
        frameDeny: true
```

Log when accessing domain.org:

```
controller-traefik-1  | 172.25.0.1 - - [24/Jan/2024:10:50:12 +0000] "GET / HTTP/1.1" 403 175 "-" "Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Mobile Safari/537.36" 331 "public_html@docker" "http://172.25.0.9:80" 0ms
```

IP Address 172.25.0.1 is gateway IP of docker compose created network.

As for plugin configuration, I've tried following:
```
disableDefault: true
trustips:
  - "172.25.0.0/16"
```

```
disableDefault: true
trustips:
  - "172.25.0.1/32"
```

```
disableDefault: true
trustips:
  - "172.25.0.12/32" # IP of container running cloudflared
```

```
disableDefault: false
```

And i always get the same log output.

I would really appreciate assistance on this.

**Comment by maretodoric** [comment]
This can be closed but here's an idea to update docs to help anyone struggling with this issue later.
You need to set following to static config, in my case in cli:

```
--entryPoints.web.forwardedHeaders.insecure
```

OR (even better, more secure) specify origin IP, IP or CIDR of your cloudflared host:
```
--entryPoints.web.forwardedHeaders.trustedIPs=127.0.0.1/32,192.168.1.7
```

Make sure the `web` in your static config points to name of your entrypoint.

Btw I've noticed that i get the same outcome (original user IP address in log file) when using following middleware:

```
http:
  middlewares:
    cfip-m:
      headers:
        customRequestHeaders:
          X-Forwarded-For: ">CF-Connecting-IP"
```

Is there something this plugin does anything extra?
