### ISSUE TITLE
[Docs] Update README regarding Traefik access log IPs

### ISSUE THREAD

**Issue by ToshY** [BetterCorp/cloudflarewarp#32]
**Problem**

Like many others, #13, #23, #25, #29, #30, I've been trying to use this plugin, in particually with a [Crowdsec ](https://www.crowdsec.net/) instance which uses the Traefik access **logs**. 

While the plugin does exactly what it says it does, fixing the headers, many (like myself) incorrectly assume that the plugin will also fix the access log with the actual user IP instead of the CloudFlare IP, which this plugin does **not**.

In order to have the user IPs instead of CloudFlare IPs in the logging, the idea is to set `trustedIPs` under the `forwardedHeaders`, see [docs](https://doc.traefik.io/traefik/routing/entrypoints/#forwarded-headers).

An example would be as follows:

<details><summary><code>static.yml</code></summary>

```yaml
entryPoints:
  websecure:
    forwardedHeaders:
      trustedIPs:
        - 173.245.48.0/20
        - 103.21.244.0/22
        - 103.22.200.0/22
        - 103.31.4.0/22
        - 141.101.64.0/18
        - 108.162.192.0/18
        - 190.93.240.0/20
        - 188.114.96.0/20
        - 197.234.240.0/22
        - 198.41.128.0/17
        - 162.158.0.0/15
        - 104.16.0.0/13
        - 104.24.0.0/14
        - 172.64.0.0/13
        - 131.0.72.0/22
        - 2400:cb00::/32
        - 2606:4700::/32
        - 2803:f800::/32
        - 2405:b500::/32
        - 2405:8100::/32
        - 2a06:98c0::/29
        - 2c0f:f248::/32
```

</details> 

or if you use environment variables for static configuration:

<details><summary><code>.env</code></summary>

```dotenv
TRAEFIK_ENTRYPOINTS_WEBSECURE_FORWARDEDHEADERS_TRUSTEDIPS="173.245.48.0/20,103.21.244.0/22,103.22.200.0/22,103.31.4.0/22,141.101.64.0/18,108.162.192.0/18,190.93.240.0/20,188.114.96.0/20,197.234.240.0/22,198.41.128.0/17,162.158.0.0/15,104.16.0.0/13,104.24.0.0/14,172.64.0.0/13,131.0.72.0/22,2400:cb00::/32,2606:4700::/32,2803:f800::/32,2405:b500::/32,2405:8100::/32,2a06:98c0::/29,2c0f:f248::/32"
```

</details> 

<sub>
IPs in the above examples are available from <a href="https://www.cloudflare.com/ips/">https://www.cloudflare.com/ips/</a>.
</sub>

---

**Suggestion**

Minor addition to the documentation to state that this plugin only fixes the headers and that additional steps have to be taken (like the examples denoted earlier) to get the actual IP changes in the access logs.
