### ISSUE TITLE
traefik 404 not found

### ISSUE THREAD

**Issue by raphhgg** [BetterCorp/cloudflarewarp#33]
When restarting Traefik after I install the plugin I have a 404 not found on Traefik's dashboard.

config.yml:
```yml
http:
  middlewares:
    crowdsec-bouncer:
      forwardauth:
        address: http://bouncer-traefik:8081/api/v1/forwardAuth
        trustForwardHeader: true    
    my-cloudflarewarp:
      plugin:
        cloudflarewarp:
          disableDefault: false
          trustip:
            - "10.10.2.0/24" # local network where my server is 
```

traefik.yml :
```yml
api:
  dashboard: true
  debug: true
entryPoints:
  http:
    address: ":80"
    http:
      middlewares:
        - cloudflarewarp@file
        - crowdsec-bouncer@file
      redirections:
        entryPoint:
          to: https
          scheme: https
  https:
    address: ":443" 
    http:
      middlewares:
        - cloudflarewarp@file
        - crowdsec-bouncer@file
serversTransport:
  insecureSkipVerify: true
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: external_proxy
  file:
    filename: /config.yml
certificatesResolvers:
  cloudflare:
    acme:
      email: email
      storage: acme.json
      dnsChallenge:
        provider: cloudflare
        # disablePropagationCheck: true # uncomment this if you have issues pulling certificates through cloudflare, By setting this flag to true disables the need to wait for the propagation of the TXT record to all authoritative name servers.
        resolvers:
          - "1.1.1.1:53"
          - "1.0.0.1:53"
log:
  level: "INFO"
  filePath: "/var/log/traefik/traefik.log"
accessLog:
  filePath: "/var/log/traefik/access.log"

experimental:
  plugins:
    cloudflarewarp:
      modulename: github.com/BetterCorp/cloudflarewarp
      version: v1.3.0
```
I thought it was maybe an compatibility error with the crowdsec bouncer but even disabling it doesn't change, I still got the 404 on traefik.

Any idea why?
