### ISSUE TITLE
Can't get real-IP 

### ISSUE THREAD

**Issue by chupacabra71** [BetterCorp/cloudflarewarp#35]
I must be doing something wrong, but i've tried every combination and cannot get the real IP to show the Cf-Connecting-IP.  this is my entrypoint:

```
entryPoints:
  websecure:
    address: ':443'
    asDefault: true
    forwardedHeaders:
      trustedIPs: &trustedIps
      # Start of Clouflare public IP list for HTTP requests
      - 173.245.48.0/20
      - 103.21.244.0/22
      - 103.22.200.0/22
      - 103.31.4.0/22
      - 141.101.64.0/18
      - 108.162.192.0/18
      - 190.93.240.0/20
      - 188.114.96.0/20
      - 197.234.240.0/22
      - 198.41.128.0/17
      - 162.158.0.0/15
      - 104.16.0.0/13
      - 104.24.0.0/14
      - 172.64.0.0/13
      - 131.0.72.0/22

      - 2400:cb00::/32
      - 2606:4700::/32
      - 2803:f800::/32
      - 2405:b500::/32
      - 2405:8100::/32
      - 2a06:98c0::/29
      - 2c0f:f248::/32
      # End of Cloudlare public IP list
    http:
      tls:
        # wildcard certificate resolver
        certResolver: cloudflare
        domains:
          - main: "*.my.tld"

  websecure-external:
    address: ':444'
    forwardedHeaders:
      # Reuse list of Cloudflare Trusted IP's above for HTTPS requests
      trustedIPs: *trustedIps 
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https


```

and this is my router:
```
http:
  routers:
    my-service-external:
      entryPoints:
        - websecure-external
      rule: "Host(`myservice.my.tld`)"
      service: my-service

      middlewares:
        - global-crowdsec@file          #crowdsec handler for security
        - global-cloudflarewarp@file

  services:
    my-service:
      loadBalancer:
        servers:
        - url: http://192.168.40.10:123
```        

when i look at the logs in CF, is see the following:
```
{
   "ClientAddr":"192.168.50.20:33334",
   "ClientHost":"192.168.50.20",    <------------ TRAEFIK IP
   "ClientPort":"33334",
   "ClientUsername":"-",
   "DownstreamContentSize":2420,
   "DownstreamStatus":200,
   "Duration":4356254,
   "OriginContentSize":2420,
   "OriginDuration":4317015,
   "OriginStatus":200,
   "Overhead":39239,
   "RequestAddr":"myservice.my.tld",
   "RequestContentSize":0,
   "RequestCount":1,
   "RequestHost":"myservice.my.tld",
   "RequestMethod":"GET",
   "RequestPath":"/",
   "RequestPort":"-",
   "RequestProtocol":"HTTP/2.0",
   "RequestScheme":"https",
   "RetryAttempts":0,
   "RouterName":"my-service-external@file",
   "ServiceAddr":"192.168.40.10:123",
   "ServiceName":"my-service@file",
   "ServiceURL":"http://192.168.40.10:123",
   "StartLocal":"2024-12-27T12:00:37.128089834-05:00",
   "StartUTC":"2024-12-27T17:00:37.128089834Z",
   "TLSCipher":"TLS_AES_128_GCM_SHA256",
   "TLSVersion":"1.3",
   "downstream_Content-Encoding":"gzip",
   "downstream_Content-Length":"2420",
   "downstream_Content-Type":"text/html; charset=utf-8",
   "downstream_Date":"Fri, 27 Dec 2024 17:00:37 GMT",
   "downstream_Referrer-Policy":"no-referrer",
   "downstream_Server":"",
   "downstream_X-Content-Type-Options":"nosniff",
   "downstream_X-Frame-Options":"SAMEORIGIN",
   "entryPointName":"websecure-external",
   "level":"info",
   "msg":"",
   "origin_Content-Encoding":"gzip",
   "origin_Content-Length":"2420",
   "origin_Content-Type":"text/html; charset=utf-8",
   "origin_Date":"Fri, 27 Dec 2024 17:00:37 GMT",
   "origin_Referrer-Policy":"no-referrer",
   "origin_Server":"",
   "origin_X-Content-Type-Options":"nosniff",
   "origin_X-Frame-Options":"SAMEORIGIN",
   "request_Accept":"text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
   "request_Accept-Encoding":"gzip, br",
   "request_Accept-Language":"en-US,en;q=0.5",
   "request_Cdn-Loop":"cloudflare; loops=1",
   "request_Cf-Connecting-Ip":"172.56.222.155",    <---------------- Client IP
   "request_Cf-Ipcountry":"US",
   "request_Cf-Ray":"8f8ade2ba8a243d4-EWR",
   "request_Cf-Visitor":"{\"scheme\":\"https\"}",
   "request_Cf-Warp-Tag-Id":"0fedde6c-4cfd-4c48-bdb1-fd16b7e8b0da",
   "request_Dnt":"1",
   "request_Priority":"u=0, i",
   "request_Sec-Fetch-Dest":"document",
   "request_Sec-Fetch-Mode":"navigate",
   "request_Sec-Fetch-Site":"none",
   "request_Sec-Fetch-User":"?1",
   "request_Sec-Gpc":"1",
   "request_Upgrade-Insecure-Requests":"1",
   "request_User-Agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:133.0) Gecko/20100101 Firefox/133.0",
   "request_X-Forwarded-Host":"myservice.my.tld",
   "request_X-Forwarded-Port":"443",
   "request_X-Forwarded-Proto":"https",
   "request_X-Forwarded-Server":"traefik",
   "request_X-Real-Ip":"192.168.50.20",     <-------------- TRAEFIK IP
   "time":"2024-12-27T12:00:37-05:00"
}
```

anyone have any idea as to what the issue could be?  i am sure it is some sort of simple issue, but having looked at it for the last few hours, i cannot see it.
